port: ":8081"
backendURL: "http://localhost:9090"
adminToken: "testToken"

db:
  host: "localhost"
  port: 33060
  user: "root"
  password: "root"
  database: "gateway"
  maxIdleConns: 10
  maxOpenConns: 100
  debug: true

log:
  path: ""
  level: "debug"

vmPool:
  size: 100
